Repository mongodb/intellij, pull requests merged in 2024-10, with the labels that each got.

#66 chore: try to cache IDEA indexes to speed up CI
  .github/workflows/quality-check.yaml
Labels: no release notes

#65 chore: support for in and nin operators INTELLIJ-78
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/IntegrationTest.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
Labels: no release notes

#70 feat: load the current database from Spring's application yaml
  CHANGELOG.md
  gradle/libs.versions.toml
  packages/mongodb-dialects/spring-criteria/build.gradle.kts
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaContextExtractor.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaContextExtractorTest.kt
Labels: feature

#72 fix(ci): change to temurin, adopt is deprecated
  .github/workflows/draft-release.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/quality-check.yaml
Labels: fix

#69 fix: fix for connection state and selection state not propagating to the Toolbar INTELLIJ-96
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/DataSourceModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/DatabaseModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/implementations/ProjectDataSourceModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/implementations/ProjectDatabaseModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/DataSourceService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbDataSourceService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/PersistentToolbarSettings.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/OpenConnectionChooserQuickFix.kt
  packages/jetbrains-plugin/src/main/resources/messages/CodeActionsBundle.properties
  packages/jetbrains-plugin/src/main/resources/messages/MdbToolbarBundle.properties
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/MongoDbRunQueryActionUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecoratorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModelTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarPopupFixture.kt
Labels: fix

#67 chore: support multiple super classes in the java driver namespace extractor INTELLIJ-105
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverNamespaceCheckLinterInspectionTest.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/adt/Either.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReference.kt
Labels: no release notes

#73 feat:(spring-criteria): Support for update operators INTELLIJ-49
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/CodeInsightTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaIndexCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaNamespaceCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringCriteriaRepository.java
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractorTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/IsCommand.kt
Labels: feature

#75 chore: fixes for failing unit test and minor UI bug
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
Labels: no release notes

#76 feat(spring-criteria): add support for not operator INTELLIJ-61
  CHANGELOG.md
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
Labels: feature

#77 feat(spring-criteria): support for in/nin operators INTELLIJ-104
  CHANGELOG.md
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
Labels: feature

#78 chore: improvements on flakiness of UI tests INTELLIJ-107
  .github/workflows/quality-check.yaml
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/MongoDbRunQueryActionUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/FixtureExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/InfoAndProgressPanelFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MdbStepLogger.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/RightToolWindowHeaderFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/UiTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/DatabaseToolWindowFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/GradleToolWindowFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbActionGutterFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarPopupFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/RightToolbarFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/idea/IdeaFrame.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/settings/SettingsUiTest.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/build.gradle.kts
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/settings.gradle.kts
Labels: no release notes

#79 feat: basic support for the @Query annotation INTELLIJ-114/INTELLIJ-117
  .gitignore
  build.gradle.kts
  buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
  packages/jetbrains-plugin/build.gradle.kts
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/.idea/gradle.xml
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/.idea/misc.xml
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/gradle/wrapper/gradle-wrapper.jar
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/gradle/wrapper/gradle-wrapper.properties
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/gradlew
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/gradlew.bat
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringQueryRepository.java
  packages/mongodb-dialects/spring-@query/build.gradle.kts
  packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialect.kt
  packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
  packages/mongodb-dialects/spring-@query/src/main/resources/build.properties
  packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/IntegrationTest.kt
  packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParserTest.kt
  settings.gradle.kts
Labels: feature

#80 chore(ci): Add a workflow to validate PR titles
  .github/workflows/check-pr-title.yml
Labels: no release notes, no-title-validation

#81 fix: makes a List assignable to simple type INTELLIJ-120
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
Labels: fix

#82 feat: delegate to intellij query runner for @Query INTELLIJ-119
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
  packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/IntegrationTest.kt
  packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasSourceDialect.kt
Labels: no release notes, feature
