Repository mongodb/intellij, pull requests merged in 2024-09, with the labels that each got.

#46 chore: connect index check linter to intellij INTELLIJ-72
  packages/jetbrains-plugin/build.gradle.kts
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/OpenDataSourceConsoleAppendingCode.kt
  packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
  packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverIndexCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaIndexCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
  packages/mongodb-dialects/mongosh/build.gradle.kts
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialect.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
  packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinter.kt
  packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinterTest.kt
  settings.gradle.kts
Labels: no release notes, feature

#48 feat: Run Java queries directly from code INTELLIJ-70
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/AbstractMongoDbCodeActionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/MongoDbCodeAction.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/DatagripConsoleEditor.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/i18n/CodeActionsMessages.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/i18n/Icons.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/OpenDataSourceConsoleAppendingCode.kt
  packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
  packages/jetbrains-plugin/src/main/resources/icons/ConsoleRun.svg
  packages/jetbrains-plugin/src/main/resources/icons/ConsoleRunDark.svg
  packages/jetbrains-plugin/src/main/resources/messages/CodeActionsBundle.properties
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/JavaDriverRunQueryCodeActionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/SpringCriteriaRunQueryCodeActionTest.kt
Labels: feature

#50 feat(toolbar): toolbar will now persist selected dataSource and database across intellij sessions and will restore them on boot INTELLIJ-65
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/DataSourceModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/DatabaseModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/implementations/ProjectDataSourceModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/implementations/ProjectDatabaseModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/DataSourceService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/EditorService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/MdbPluginDisposable.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/ToolbarSettings.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/InMemoryToolbarSettings.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbDataSourceService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/PersistentToolbarSettings.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/OpenConnectionChooserQuickFix.kt
  packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecoratorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
Labels: feature

#51 fix: concurrent access to mongosh is disallowed INTELLIJ-89
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
Labels: fix, no release notes

#53 fix: for persisting datastore selection for a workspace between IntelliJ sessions INTELLIJ-83
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/PersistentToolbarSettings.kt
Labels: fix

#52 feat: query generation to run java queries in datagrip's console INTELLIJ-73
  CHANGELOG.md
  packages/mongodb-access-adapter/datagrip-access-adapter/build.gradle.kts
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/mongosh/build.gradle.kts
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/Context.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt
Labels: feature

#57 chore: add plugin version to telemetry and logs
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/LogMessage.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryService.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/LogMessageTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryServiceTest.kt
Labels: no release notes

#55 chore: instead of running the whole pipeline again, only allow drafts when main is green already
  .github/workflows/draft-release.yaml
  build.gradle.kts
Labels: fix, no release notes

#54 feat: trigger autocompletion automatically in a MongoDB query INTELLIJ-91
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbAutocompletionPopupHandler.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
  packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
Labels: feature

#58 fix: avoid running queries if they are incomplete INTELLIJ-97
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbe.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbe.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbe.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/PluginActivatedProbe.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
  packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
  packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinter.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Namespace.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NamespaceTest.kt
Labels: fix

#60 fix: BsonType not assignable to BsonArray INTELLIJ-94
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
Labels: fix

#61 chore: support parenthesized expressions in the java driver INTELLIJ-85
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
Labels: fix, no release notes

#63 fix: do not crash if we can't infer the namespace INTELLIJ-103
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
Labels: fix, no release notes

#62 chore: support for not in query generation INTELLIJ-77
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
Labels: no release notes

#64 chore: fix versionBump after diktat formatting broke it
  build.gradle.kts
Labels: no release notes
