Repository mongodb/intellij, pull requests merged in 2025-06, with the labels that each got.

#222 chore: keep only verifyPlugin in the scheduled and make versionBump cacheable
  .github/workflows/act-draft-release.yaml
  .github/workflows/pr-quality-gate.yaml
  build.gradle.kts
Labels: no-title-validation, skip-spec-check

#227 fix(modal): databases were not loading in the run query modal INTELLIJ-340
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
Labels: no release notes

#239 chore: fix README.md links to images
  README.md
Labels: no-title-validation

#240 chore: add labels to README.md
  README.md
Labels: no-title-validation

#248 chore: clean up a bit the README.md
  README.md
Labels: no-title-validation

#249 chore: fix ga release
  .github/workflows/act-publish-release.yaml
Labels: no-title-validation

#251 Revert "fix: show no index warnings when a query has no filters INTELLIJ-360"
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/performance/MongoDbQueryNotUsingFilters.kt
  packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
  packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
  packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlayTest.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/QueryInsight.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingFiltersInspection.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexEffectivelyInspection.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspection.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingFiltersInspectionTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionEffectivelyTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionTest.kt
Labels: no-title-validation

#254 fix: README pointing to the wrong repository
  README.md
Labels: no-title-validation, skip-spec-check

#253 chore: adds additional tests for NamespaceExtractor
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
Labels: no-title-validation
