Repository mongodb/intellij, pull requests merged in 2025-02, with the labels that each got.

#135 feat: adds support for parsing `Sort` objects attached to `Query` objects in spring data mongodb INTELLIJ-199
  CHANGELOG.md
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/BookRepository.java
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QuerySortParser.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/SortStageParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
Labels: feat

#136 chore: consolidate engines into a single package INTELLIJ-203
  .github/workflows/check-changelog.yml
  build.gradle.kts
  packages/jetbrains-plugin/build.gradle.kts
  packages/mongodb-dialects/mongosh/build.gradle.kts
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-linting-engine/build.gradle.kts
  packages/mongodb-mql-engines/build.gradle.kts
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/autocomplete/Autocompletion.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinter.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinter.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/autocomplete/AutocompletionTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinterTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinterTest.kt
  settings.gradle.kts
Labels: no release notes

#137 chore: remove the usage of runBlocking in isolated modules INTELLIJ-204
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/FieldCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/NamespaceCheckInspectionBridge.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Aggregate.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Match.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Find.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Query.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/References.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Sort.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Update.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/AddFieldsTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/AggregateTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/GroupTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/MatchTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/ProjectTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/SortTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/UnwindTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/FindTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/UpdateTest.kt
  packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinter.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinterTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
Labels: no release notes

#92 chore: mql specs
  packages/mongodb-mql-model/src/docs/md/bson-type/bson-type.md
  packages/mongodb-mql-model/src/docs/md/mql-component/mql-component.md
  packages/mongodb-mql-model/src/docs/md/mql-dialect/mql-dialect.md
  packages/mongodb-mql-model/src/docs/md/mql-engine/mql-engine.md
  packages/mongodb-mql-model/src/docs/md/mql-query/mql-query.md
Labels: help wanted, no release notes, no-title-validation

#110 fix(ci): fix packaging of the segment key INTELLIJ-148
  .github/workflows/quality-check.yaml
  .run/Open RemoteRobot UI.run.xml
  .run/Start IDE with Plugin.run.xml
  CONTRIBUTING.md
  buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
  gradle/libs.versions.toml
  gradle/run-ui-test.sh
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/MongoDbRunQueryActionUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/FixtureExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/InfoAndProgressPanelFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MdbStepLogger.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/RightToolWindowHeaderFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/UiTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/BrowserSettingsFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/DatabaseToolWindowFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/GradleToolWindowFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbActionGutterFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarPopupFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MongoDbSettingsFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/RightToolbarFixture.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/idea/IdeaFrame.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/settings/SettingsUiTest.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/resources/build.properties
  packages/mongodb-dialects/java-driver/src/main/resources/build.properties
  packages/mongodb-dialects/mongosh/src/main/resources/build.properties
  packages/mongodb-dialects/spring-@query/src/main/resources/build.properties
  packages/mongodb-dialects/spring-criteria/src/main/resources/build.properties
Labels: fix

#138 chore: use the mql model instead of BSON for our own queries INTELLIJ-206
  buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
  gradle/libs.versions.toml
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelectorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/meta/BuildInformationTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbeTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
  packages/jetbrains-plugin/src/test/resources/build.properties
  packages/jetbrains-plugin/src/test/resources/local-atlas.yml
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepositoryClone.java
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringCriteriaRepository.java
  packages/mongodb-access-adapter/build.gradle.kts
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/DataGripBasedReadModelProvider.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/DataGripBasedReadModelProviderTest.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfo.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollections.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListDatabases.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfoTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQueryTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollectionsTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Aggregate.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Limit.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Query.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Sort.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/AggregateTest.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/FindTest.kt
  packages/mongodb-mql-model/src/docs/md/bson-type/bson-type.md
  packages/mongodb-mql-model/src/docs/md/mql-component/mql-component.md
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReference.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasExplain.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
Labels: no release notes

#140 feat(spring): support for Reactive Spring Data INTELLIJ-230
  CHANGELOG.md
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/ReactiveAggregationStagesParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/ReactiveSpringCriteriaDialectParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/AddFieldsStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/GroupStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/MatchStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/ProjectStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/SortStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/UnwindStageParserTest.kt
Labels: feat

#143 chore: add ineffective index usage to the index analyser INTELLIJ-216
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverIndexCheckLinterInspectionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaIndexCheckLinterInspectionTest.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQueryTest.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinter.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinterTest.kt
Labels: no release notes

#144 chore: mark queries with a ratio of returned docs vs loaded docs greater than 50 as ineffective INTELLIJ-218
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQueryTest.kt
Labels: no release notes

#145 chore: implement BsonEnum for Java enums INTELLIJ-224
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtilTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
  packages/mongodb-mql-model/src/docs/md/bson-type/bson-type.md
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
Labels: no release notes

#148 fix(build): gracefully fail to default values if the JVM does not allow us to load the plugin metadata INTELLIJ-231
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/BuildInformation.kt
Labels: fix

#146 chore: support for the sibling queries finder, so we have access to all queries for a single namespace INTELLIJ-213
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/CachedQueryServiceTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/SiblingQueriesFinder.kt
Labels: no release notes

#149 feat(indexes): improve index suggestions by using the ESR guidelines INTELLIJ-222
  CHANGELOG.md
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasValueReference.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/Named.kt
Labels: feat

#150 chore: adds data distribution based on sample docs in CollectionSchema INTELLIJ-214
  .github/workflows/check-changelog.yml
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/CollectionSchema.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/DataDistribution.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/DataDistributionTest.kt
Labels: no release notes

#151 feat(indexes): support for index consolidation for multiple queries in the same collection INTELLIJ-219
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
  packages/mongodb-dialects/build.gradle.kts
  packages/mongodb-dialects/java-driver/build.gradle.kts
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
  packages/mongodb-mql-engines/src/docs/md/index-analyzer/index-analyzer.md
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidationTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelAssertions.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
Labels: feat

#153 feat: consider selectivity over cardinality when sorting index fields for index suggestion INTELLIJ-232
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/GroupStageParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/ReactiveSpringCriteriaDialectParserTest.kt
  packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/GroupStageParserTest.kt
  packages/mongodb-mql-engines/src/docs/md/index-analyzer/index-analyzer.md
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/DataDistribution.kt
  packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/DataDistributionTest.kt
Labels: feat

#154 chore: get rid of bson in the access adapter INTELLIJ-207
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbeTest.kt
  packages/mongodb-access-adapter/build.gradle.kts
  packages/mongodb-access-adapter/datagrip-access-adapter/build.gradle.kts
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/IntegrationTest.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfo.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollections.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListDatabases.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriverTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfoTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollectionsTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-mql-model/src/docs/md/mql-component/mql-component.md
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasRunCommand.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/IsCommand.kt
Labels: no release notes

#155 chore: migrate to plugin sdk 2.+ INTELLIJ-202
  .github/workflows/act-draft-release.yaml
  .github/workflows/act-publish-release.yaml
  .github/workflows/check-changelog.yml
  .github/workflows/check-mql-spec.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/codeql.yml
  .github/workflows/pr-metadata-verification.yaml
  .github/workflows/pr-quality-gate.yaml
  .github/workflows/sch-codeql.yml
  .gitignore
  .idea/runConfigurations/MongoDB_6_x.xml
  .idea/runConfigurations/MongoDB_7_x.xml
  .idea/runConfigurations/MongoDB_8_x.xml
  .idea/runConfigurations/Start_IDE_with_Plugin.xml
  CHANGELOG.md
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.mongodb.intellij.isolated-module.gradle.kts
  buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
  etc/docker-compose.yaml
  gradle.properties
  gradle/libs.versions.toml
  packages/jetbrains-plugin/build.gradle.kts
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/BuildInformation.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryService.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/SpringCriteriaRunQueryCodeActionTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/CachedQueryServiceTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProviderTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModelTest.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
  packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/meta/BuildInformationTest.kt
  packages/jetbrains-plugin/src/test/resources/build.properties
  packages/jetbrains-plugin/src/test/resources/messages/LLMInstallerBundle.properties
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/IntegrationTest.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/test/resources/messages/LLMInstallerBundle.properties
  packages/mongodb-dialects/java-driver/build.gradle.kts
  packages/mongodb-dialects/java-driver/src/test/resources/messages/LLMInstallerBundle.properties
  packages/mongodb-dialects/spring-@query/src/test/resources/messages/LLMInstallerBundle.properties
  packages/mongodb-dialects/spring-criteria/src/test/resources/messages/LLMInstallerBundle.properties
  qodana.yml
Labels: no release notes

#156 feat: consider sort direction specified in user code when generating indexes INTELLIJ-226
  CHANGELOG.md
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
  packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQueryTest.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelAssertions.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasValueReference.kt
Labels: feat, skip-spec-check

#158 chore: fixed some qodana complains
  README.md
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
  gradle/libs.versions.toml
  packages/jetbrains-plugin/src/jmh/kotlin/com/mongodb/jbplugin/jmh/SampleBenchmark.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/MdbPluginDisposable.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/InMemoryToolbarSettings.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbDataSourceService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/settings/PluginSettingsConfigurable.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfo.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListDatabases.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/Context.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Query.kt
  packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFilter.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasSourceDialect.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasUpdates.kt
  packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/IsCommand.kt
  qodana.yml
Labels: no release notes, no-title-validation, skip-spec-check

#159 chore: support for partialFilterExpressions in indexes INTELLIJ-227
  gradle/pre-commit
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryNamespaceInlay.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/CreateIndexIntentionProbe.kt
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/QueryRunProbe.kt
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Find.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
  packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
Labels: skip-spec-check

#160 chore: support for partialFilterExpression in the index consolidation INTELLIJ-223
  CHANGELOG.md
  packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
  packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/OrderRepository.java
  packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
  packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
  packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
  packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
  packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexQueryFieldUsage.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidationTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelAssertions.kt
  packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
Labels: skip-spec-check

#161 chore: qodana should not block a release
  build.gradle.kts
Labels: no release notes, no-title-validation, skip-spec-check

#162 chore: verify plugin now requires the segment api key
  .github/workflows/act-draft-release.yaml
  buildSrc/src/main/kotlin/com.mongodb.intellij.isolated-module.gradle.kts
Labels: fix, no release notes, no-title-validation, skip-spec-check
